# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: sudo npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker info
      - run: docker build --build-arg NPM_TOKEN=$NPM_TOKEN -t leverj/leverj-mm:$CIRCLE_BRANCH .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push leverj/leverj-mm
      - run: docker logout
      - run: rm -f ~/.npmrc
